added disable option and values as object
itgenio/uikit pull request #113
Opened 2022-11-18 09:15 UTC by AndreevAndrey

Добавлена возможность передавать в options object с обязательным ключом key, сохранение в values объектов  с нужными данными, возможность дизейблить чекбоксы и  исключать их при выборе всех параметров

2022-11-22 16:21 UTC, Pavel-R requested changes

2022-11-22 16:21 UTC, Pavel-R commented on gkit/src/components/multiSelect/index.tsx
> +        id-qa={classNames({ [`${idQa}-option-${isValueObj ? value.key : value}`]: idQa })}
Можно вынести в переменную `key` и использовать ее тут и на строках 133, 141 и 148.

2022-11-22 16:21 UTC, Pavel-R commented on gkit/src/components/multiSelect/index.tsx
> +export type MultiSelectOption<T extends Object = {}> = {
Нет разрыва между 23 и 24 строками

2022-11-22 16:21 UTC, Pavel-R commented on gkit/src/components/checkbox/style.less
> +      cursor: auto;
Кажется, что нужен pointer - иначе над текстом он меняется на `text`, а над чекбоксом  `default`. Тут и в других кейсах.

2022-11-23 06:33 UTC, AndreevAndrey commented on gkit/src/components/checkbox/style.less
> +      cursor: auto;
pointer выше задан. Добавлю тогда default, если disabled

2022-11-23 08:21 UTC, Pavel-R approved these changes

2022-12-02 10:17 UTC, merged