Add group in multiselect and update in select
itgenio/uikit pull request #95
Opened 2022-10-10 14:35 UTC by Rostia

2022-10-11 10:41 UTC, Pavel-R commented on gkit/src/components/multiSelect/index.tsx
> +type Option = { label: string; value: Value; group: string };
`group` должен быть опциональным.

2022-10-11 11:19 UTC, Pavel-R requested changes

2022-10-11 12:28 UTC, Rostia commented on gkit/src/components/multiSelect/index.tsx
> +  divideByGroups?: boolean;
Сделал

2022-10-11 12:29 UTC, Rostia commented on gkit/src/components/select/index.tsx
>    divideByGroups?: boolean;
Поправил

2022-10-11 12:29 UTC, Rostia commented on gkit/src/components/multiSelect/index.tsx
> +type Option = { label: string; value: Value; group: string };
Поправил

2022-10-12 10:00 UTC, Pavel-R approved these changes

2022-10-12 10:31 UTC, merged